### ISSUE TITLE
`generate-github-markdown-css` currently crashes

### ISSUE THREAD

**Issue by wooorm** [sindresorhus/generate-github-markdown-css#17]
```js
import generateGithubMarkdownCss from 'generate-github-markdown-css'

const result = await generateGithubMarkdownCss()

console.log(result)
```

```
/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:62
    var err = new Error(options.source + ':' + lineno + ':' + column + ': ' + msg);
              ^

Error: undefined:1:2672: missing '}'
    at error (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:260:26)
    at rule (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:561:21)
    at rules (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:118:70)
    at stylesheet (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:81:21)
    at module.exports [as parse] (/Users/tilde/Projects/oss/starry-night/node_modules/css/lib/parse/index.js:565:20)
    at getCSS (file:///Users/tilde/Projects/oss/starry-night/node_modules/generate-github-markdown-css/index.js:287:19)
    at async file:///Users/tilde/Projects/oss/starry-night/example.js:3:16 {
  reason: "missing '}'",
  filename: undefined,
  line: 1,
  column: 2672,
  source: '.Button-label{line-height:1.66667;line-height:var(--primer-text-body-lineHeight-small,1.66667)}.Button-content>:not(:last-child){margin-right:4px;margin-right:var(--primer-control-small-gap,4px)}}.Button--large{gap:8px;gap:var(--pr...
```

Maybe GH is currently shipping broken CSS? Or using some fancy new CSS feature that `css` doesn’t understand yet?

```
$ npm ls css
@wooorm/starry-night@1.3.0 /Users/tilde/Projects/oss/starry-night
├── css@3.0.0
└─┬ generate-github-markdown-css@5.0.1
  └── css@3.0.0 deduped
```

**Comment by hyrious** [comment]
Yes, it seems that they published a minified SCSS file.

https://github.com/community/community/discussions/35511

**Comment by hyrious** [comment]
Seems ok now.
